name: Test

on:
    push:
        branches: [ develop ]
    pull_request:

jobs:
    tests:
        strategy:
            matrix:
                os: [Ubuntu]
                php: [5.5, 5.6]

                include:
                    - os: Ubuntu
                      os-version: ubuntu-latest

        name: ${{ matrix.os }} - PHP ${{ matrix.php }}

        runs-on: ${{ matrix.os-version }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v1

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: posix, dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
                  coverage: none

            - name: Install dependencies
              run: composer update --prefer-stable --prefer-dist --no-interaction --no-suggest --ignore-platform-reqs

            - name: Run tests
              run: vendor/bin/phpunit

            - name: Code Coverage
              run: |
                phpunit --coverage-clover=coverage.clover
                wget https://scrutinizer-ci.com/ocular.phar
                php ocular.phar code-coverage:upload --format=php-clover coverage.clover


